-- Run this in Supabase SQL Editor if you see:
-- "Could not find the table 'public.signals' in the schema cache"

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('offer', 'answer', 'candidate')),
  payload jsonb not null,
  sender text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_signals_created_at on public.signals (created_at);

alter table public.signals enable row level security;

drop policy if exists "signals_rw" on public.signals;
create policy "signals_rw" on public.signals
for all
to anon, authenticated
using (true)
with check (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.signals;
  exception
    when duplicate_object then null;
  end;
end $$;
