create extension if not exists "pgcrypto";

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('offer', 'answer', 'candidate')),
  payload jsonb not null,
  sender text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_signals_created_at on public.signals (created_at);

create table if not exists public.call_status (
  id bigint primary key,
  status text not null check (status in ('idle', 'ringing', 'accepted', 'declined', 'ended')),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

insert into public.call_status (id, status)
values (1, 'idle')
on conflict (id) do nothing;

-- Optional table if you prefer DB-level presence tracking in addition to Realtime Presence.
create table if not exists public.presence (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  joined_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.signals enable row level security;
alter table public.call_status enable row level security;
alter table public.presence enable row level security;

-- Private app with shared password: allow anon authenticated frontend to read/write signaling.
-- Restrict by project URL secrecy + shared room password in UI.
drop policy if exists "signals_rw" on public.signals;
create policy "signals_rw" on public.signals
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "call_status_rw" on public.call_status;
create policy "call_status_rw" on public.call_status
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "presence_rw" on public.presence;
create policy "presence_rw" on public.presence
for all
to anon, authenticated
using (true)
with check (true);

do $$
begin
  begin
    alter publication supabase_realtime add table public.signals;
  exception
    when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.call_status;
  exception
    when duplicate_object then null;
  end;
end $$;
